namenode:
    image: gelog/hadoop
    ports: 
        - "50070:50070"
    command: hdfs namenode
    hostname: hdfs-namenode

datanode:
    image: gelog/hadoop
    command: hdfs datanode
    ports:
# The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
        - "50075"
    links:
        - namenode:hdfs-namenode

secondarynamenode:
    image: gelog/hadoop
    command: hdfs secondarynamenode
    ports:
        - "50090:50090"
    links:
        - namenode:hdfs-namenode

yarn:
    image: gelog/hadoop
    command: /usr/local/bin/start-yarn.sh
    ports:
        - "8088:8088"
        - "8042:8042"
    links:
        - datanode:hdfs-datanode1
        - namenode:hdfs-namenode
    volumes:
        - $HOME/data/hadoop/hdfs:/data
    hostname: yarn