version: '2'
services:
    namenode:
        image: cfournie/oozie
        ports: 
            - "50070:50070"
        command: hdfs namenode
        hostname: hdfs-namenode

    datanode:
        image: cfournie/oozie
        command: hdfs datanode
        ports:
    # The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
            - "50075"
        links:
            - namenode:hdfs-namenode
        depends_on:
          - secondarynamenode
          - namenode

    secondarynamenode:
        image: cfournie/oozie
        command: hdfs secondarynamenode
        ports:
            - "50090:50090"
        links:
            - namenode:hdfs-namenode
        depends_on:
          - namenode

    httpfs:
        image: cfournie/oozie
        command: /usr/local/hadoop/sbin/httpfs.sh run
        ports:
            - "14000:14000"
        links:
            - datanode:hdfs-datanode1
            - namenode:hdfs-namenode
        hostname: httpfs
        depends_on:
          - namenode
          - datanode

    resourcemanager:
        image: cfournie/oozie
        command: yarn resourcemanager
        ports:
            - "8088:8088"
        links:
            - datanode:hdfs-datanode1
            - namenode:hdfs-namenode
        volumes:
            - $HOME/data/hadoop/hdfs:/data
        hostname: resourcemanager
        depends_on:
          - datanode
          - namenode

    nodemanager:
        image: cfournie/oozie
        command: yarn nodemanager
        ports:
            - "8042:8042"
        links:
            - resourcemanager:resourcemanager
            - datanode:hdfs-datanode1
            - namenode:hdfs-namenode
        volumes:
            - $HOME/data/hadoop/hdfs:/data
        hostname: nodemanager
        depends_on:
          - datanode
          - namenode
          - resourcemanager
          
    jobhistory:
        image: cfournie/oozie
        command: /usr/local/hadoop/bin/mapred --config /usr/local/hadoop/etc/hadoop historyserver
        ports:
          - "19888:19888"
        links:
            - datanode:hdfs-datanode1
            - namenode:hdfs-namenode
            - nodemanager:nodemanager
            - resourcemanager:resourcemanager
        hostname: jobhistory
        depends_on:
          - resourcemanager
          - nodemanager
          - namenode
          - datanode        
          
    oozie:
        image: cfournie/oozie
        command: /usr/local/bin/start-oozie.sh
        ports:
            - "11000:11000"
        links:
            - datanode:hdfs-datanode1
            - namenode:hdfs-namenode
            - jobhistory:jobhistory
            - nodemanager:nodemanager
            - resourcemanager:resourcemanager
        hostname: oozie
        depends_on:
          - resourcemanager
          - nodemanager
          - namenode
          - datanode
          - jobhistory
